# Generated by Django 2.0.7 on 2018-08-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=250, null=True)),
                ('contenido', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido_Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=250, null=True)),
                ('contenido', models.CharField(blank=True, max_length=5000, null=True)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Descripcion_Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('id_autor', models.ManyToManyField(to='LeoBookAPI.Autor')),
                ('id_categoria', models.ManyToManyField(to='LeoBookAPI.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('id_descripcion_venta', models.ManyToManyField(to='LeoBookAPI.Descripcion_Venta')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('estado', models.BooleanField(default=False)),
                ('id_libro', models.ManyToManyField(to='LeoBookAPI.Libro')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=250)),
                ('is_staff', models.BooleanField(default=True)),
                ('id_autor_fav', models.ManyToManyField(to='LeoBookAPI.Autor')),
                ('id_libro_fav', models.ManyToManyField(to='LeoBookAPI.Libro')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_usuario',
            field=models.ManyToManyField(to='LeoBookAPI.Usuario'),
        ),
        migrations.AddField(
            model_name='registro_ventas',
            name='id_usuario',
            field=models.ManyToManyField(to='LeoBookAPI.Usuario'),
        ),
        migrations.AddField(
            model_name='descripcion_venta',
            name='id_libro',
            field=models.ManyToManyField(to='LeoBookAPI.Libro'),
        ),
    ]
