# Generated by Django 2.0.7 on 2018-08-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeoBookAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido_blog',
            name='autor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contenido_blog',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
