# Generated by Django 2.0.7 on 2018-08-26 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeoBookAPI', '0004_auto_20180826_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='image',
        ),
    ]
