# Generated by Django 2.0.7 on 2018-09-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeoBookAPI', '0006_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('libro', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
