# Generated by Django 2.0.1 on 2018-09-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeoBookAPI', '0008_auto_20180905_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion_venta',
            name='libro',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
