# Generated by Django 2.0.7 on 2018-08-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=250, null=True)),
                ('contenido', models.CharField(blank=True, max_length=250, null=True)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeoBook.Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido_Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=250, null=True)),
                ('contenido', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha', models.DateField()),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeoBook.Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Descripcion_Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('id_autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LeoBook.Autor')),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LeoBook.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('id_descripcion_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LeoBook.Descripcion_Venta')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=250)),
                ('id_autor_fav', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LeoBook.Autor')),
                ('id_libro_fav', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LeoBook.Libro')),
                ('id_reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LeoBook.Reserva')),
            ],
        ),
        migrations.AddField(
            model_name='registro_ventas',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LeoBook.Usuario'),
        ),
        migrations.AddField(
            model_name='libro',
            name='id_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LeoBook.Reserva'),
        ),
        migrations.AddField(
            model_name='descripcion_venta',
            name='id_libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LeoBook.Libro'),
        ),
    ]
