# Generated by Django 2.0.1 on 2018-08-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.FloatField()),
                ('fecha_emision', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha_publicacion', models.DateTimeField()),
                ('precio', models.FloatField()),
                ('autor', models.ManyToManyField(to='LeoBook.Autor')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=12)),
                ('rol', models.CharField(max_length=13)),
                ('fecha_registro', models.DateTimeField()),
                ('autores', models.ManyToManyField(to='LeoBook.Autor')),
                ('libros', models.ManyToManyField(to='LeoBook.Libro')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='libros',
            field=models.ManyToManyField(to='LeoBook.Libro'),
        ),
        migrations.AddField(
            model_name='compra',
            name='user',
            field=models.ManyToManyField(to='LeoBook.User'),
        ),
    ]
