# Generated by Django 2.0.1 on 2018-08-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeoBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
