# Generated by Django 2.0.1 on 2018-09-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion_Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('libro', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('usuario', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('libro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('libro', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
